### ISSUE TITLE
I have code for you

### ISSUE THREAD

**Issue by thswanson97** [aktaboot/AMAVillager#1]
Hello,

I have some time keeping code I'd like to commit to the project. Can you give me PR/push/pull permissions? 

Thanks!

**Comment by thswanson97** [comment]
The code tracks time taken to solve each quiz and averages the time taken to solve over a session.

**Comment by aktaboot** [comment]
Hey !
Thanks a lot, I have been wanting to implement that but was working on exporting this to an executable or a webapp !
You can do pull requests without having any access, from a [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) !
I will give you contributor permissions anyway :)

**Comment by thswanson** [comment]
I'll get that taken care of then! Thanks!

**Comment by thswanson** [comment]
Yeah, I saw that people wanted web functionality, looks like you at least have that started !
